export default {
  AnimalsEnDe: [
    { word: "cat", translation: "Katze" },
    { word: "dog", translation: "Hund" },
    { word: "elephant", translation: "Elefant" },
    { word: "lion", translation: "Löwe" },
    { word: "tiger", translation: "Tiger" },
    { word: "giraffe", translation: "Giraffe" },
    { word: "monkey", translation: "Affe" },
    { word: "horse", translation: "Pferd" },
    { word: "rabbit", translation: "Hase" },
    { word: "bear", translation: "Bär" },
    { word: "zebra", translation: "Zebra" },
    { word: "penguin", translation: "Pinguin" },
    { word: "kangaroo", translation: "Känguru" },
    { word: "dolphin", translation: "Delfin" },
    { word: "whale", translation: "Wal" },
    { word: "shark", translation: "Hai" },
    { word: "octopus", translation: "Tintenfish" },
    { word: "crocodile", translation: "Krokodil" },
    { word: "parrot", translation: "Papagei" },
    { word: "snake", translation: "Schlange" },
  ],

  FoodEnDe: [
    { word: "apple", translation: "Apfel" },
    { word: "banana", translation: "Banane" },
    { word: "chocolate", translation: "Schokolade" },
    { word: "bread", translation: "Brot" },
    { word: "cheese", translation: "Käse" },
    { word: "milk", translation: "Milch" },
    { word: "cake", translation: "Kuchen" },
    { word: "pizza", translation: "Pizza" },
    { word: "spaghetti", translation: "Spaghetti" },
    { word: "rice", translation: "Reis" },
    { word: "lettuce", translation: "Salat" },
    { word: "tomato", translation: "Tomate" },
    { word: "carrot", translation: "Karotte" },
    { word: "potato", translation: "Kartoffel" },
    { word: "onion", translation: "Zwiebel" },
    { word: "chicken", translation: "Huhn" },
    { word: "beef", translation: "Rindfleisch" },
    { word: "fish", translation: "Fisch" },
    { word: "soup", translation: "Suppe" },
    { word: "juice", translation: "Saft" },
  ],

  SportsEnDe: [
    { word: "soccer", translation: "Fußball" },
    { word: "basketball", translation: "Basketball" },
    { word: "tennis", translation: "Tennis" },
    { word: "swimming", translation: "Schwimmen" },
    { word: "cycling", translation: "Radfahren" },
    { word: "running", translation: "Laufen" },
    { word: "volleyball", translation: "Volleyball" },
    { word: "golf", translation: "Golf" },
    { word: "hockey", translation: "Hockey" },
    { word: "skiing", translation: "Skifahren" },
    { word: "boxing", translation: "Boxen" },
    { word: "wrestling", translation: "Ringkampf" },
    { word: "athletics", translation: "Leichtathletik" },
    { word: "badminton", translation: "Badminton" },
    { word: "rugby", translation: "Rugby" },
    { word: "surfing", translation: "Surfen" },
    { word: "karate", translation: "Karate" },
    { word: "gymnastics", translation: "Gymnastik" },
    { word: "table tennis", translation: "Tischtennis" },
    { word: "baseball", translation: "Baseball" },
  ],
};
