export default {
  wordPairs: [
    { word: "cat", translation: "Katze" },
    { word: "dog", translation: "Hund" },
    { word: "elephant", translation: "Elefant" },
    { word: "lion", translation: "Löwe" },
    { word: "tiger", translation: "Tiger" },
    { word: "giraffe", translation: "Giraffe" },
    { word: "monkey", translation: "Affe" },
    { word: "horse", translation: "Pferd" },
    { word: "rabbit", translation: "Hase" },
    { word: "bear", translation: "Bär" },
    { word: "zebra", translation: "Zebra" },
    { word: "penguin", translation: "Pinguin" },
    { word: "kangaroo", translation: "Känguru" },
    { word: "dolphin", translation: "Delfin" },
    { word: "whale", translation: "Wal" },
    { word: "shark", translation: "Hai" },
    { word: "octopus", translation: "Oktopus" },
    { word: "crocodile", translation: "Krokodil" },
    { word: "parrot", translation: "Papagei" },
    { word: "snake", translation: "Schlange" },
  ],
};
